[book]
authors = ["saplyn"]
language = "en"
multilingual = false
src = "src"
title = "Lyn Notebook"

[output.html.fold]
enable = true

[output.html]
site-url = "/lynnotebook/"
git-repository-url = "https://github.com/Saplyn/lynnotebook"
edit-url-template = "https://github.com/Saplyn/lynnotebook/edit/main/{path}"
