[book]
authors = ["saplyn"]
language = "en"
multilingual = false
src = "src"
title = "Lyn Notebook"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/Saplyn/saplyn.github.io"
edit-url-template = "https://github.com/Saplyn/saplyn.github.io/edit/main/{path}"
