[book]
authors = ["saplyn"]
language = "en"
multilingual = false
src = "src"
title = "[boolyn] Lyn Notebook"

[output.html.fold]
enable = true

[output.html]
site-url = "/boolyn/"
git-repository-url = "https://github.com/Saplyn/boolyn"
edit-url-template = "https://github.com/Saplyn/boolyn/edit/main/{path}"
